# Generated by Django 5.1.6 on 2025-03-04 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_student_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='file',
        ),
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
    ]
